wallpaper {
	monitor =
	path = ~/Wallpapers/france_river.jpg
	fit_mode = cover
}

# wallpaper {
#     monitor = DP-3
#     path = ~/myFile.jxl
#     fit_mode = cover
# }

preload = ~/Wallpapers/france_river.jpg


