# wallpaper {
# 	monitor = eDP-1
# 	path = ~/Wallpapers/france_river.jpg
# 	fit_mode = cover
# }

# wallpaper {
#     monitor = DP-3
#     path = ~/myFile.jxl
#     fit_mode = cover
# }

preload = ~/Wallpapers/france_river.jpg

wallpaper = eDP-1, ~/Wallpapers/france_river.jpg

