$font = MonaspiceRnNerd Font
$fg_color = rgb(255, 255, 255)
$background = /home/odo59/Wallpapers/botanical_gardens.jpg

general {
    hide_cursor = true
    ignore_empty_input = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = $background
    color = rgb(0,0,0)
}

input-field {
    monitor =
    position = 0, -10%
    size = 20%, 8%
    outline_thickness = 5
    inner_color = rgba(0, 0, 0, 0)
    outer_color = $fg_color


    fade_on_empty = false

    font_family = $font
    font_color = $fg_color
    placeholder_text =
    fail_text =


    dots_spacing = 0.3
    dots_size = 0.2

    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 150
    font_family = $font

    position = 0, 10%
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    font_size = 40
    font_family = $font

    position = 0, 2%
    halign = center
    valign = center
}
