#!/usr/bin/env bash

STATE_FILE="/tmp/quickshell-volume"

# Defaults
VOL=50
MUTED=0

# Load state if it exists
if [ -f "$STATE_FILE" ]; then
    read VOL MUTED < "$STATE_FILE"
fi

STEP=5

showvolume () {
    eww update volumepercent=$VOL
    eww update volumemuted=$MUTED
    eww update openedtime=`date +%s%3N`
    eww update volumewindowvisible=true
    eww active-windows | grep volumepopup || eww open volumepopup
}

case "$1" in
    up)
        VOL=$((VOL + STEP))
        [ "$VOL" -gt 100 ] && VOL=100
        wpctl set-volume @DEFAULT_AUDIO_SINK@ "$(awk "BEGIN {print $VOL/100}")"
        MUTED=0
        wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
        eww update volumepercent=$(VOL)
        showvolume
        ;;
    down)
        VOL=$((VOL - STEP))
        [ "$VOL" -lt 0 ] && VOL=0
        wpctl set-volume @DEFAULT_AUDIO_SINK@ "$(awk "BEGIN {print $VOL/100}")"
        eww update volumepercent=$(VOL)
        showvolume
        ;;
    mute)
        if [ "$MUTED" -eq 1 ]; then
            MUTED=0
            wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
        else
            MUTED=1
            wpctl set-mute @DEFAULT_AUDIO_SINK@ 1
        fi
        showvolume
        ;;
    getpercentage)
        echo $VOL
        ;;
    getmuted)
        echo $MUTED
        ;;
esac

echo "$VOL $MUTED" > "$STATE_FILE"